config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'pages#home'
  
  resources :weddings do
    collection do
      get :weddings
    end
    resources :roles, :only => [:index, :create, :destroy]
  end

  resources :tasks, :except => [:show]
 
  resources :users, :only => [] do
    collection do
      get :authorise_facebook
    end
  end

  resource :user, :only => [:show] 
  
  get 'facebook_oauth_callback', { #create verb
    :to => 'users#facebook_oauth_callback', #create action
    :as => :facebook_oauth_callback #create path helper
  }

  end

app/models/group.rb
class Group < ActiveRecord::Base
  belongs_to :wedding
  belongs_to :owner, :class_name => "User", :foreign_key => :owner_id
  has_many :tasks

  before_save :create_facebook_group 

  def create_facebook_group
    @graph = Koala::Facebook::API.new(owner.access_token)
    @graph.put_wall_post("Just created a group!", {"name" => "wedding grp", "link" => "http://www.example.com/", "caption" => "{*actor*} posted a new review", "description" => "This is a longer description of the attachment", "picture" => "http://www.example.com/thumbnail.jpg"})
  end

end

app/models/role.rb
class Role < ActiveRecord::Base
  belongs_to :user
  belongs_to :wedding  
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :wedding
  belongs_to :group
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :provider
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, 
  :recoverable, :rememberable, :trackable, :validatable 

  has_many :roles
  has_many :weddings, :through => :roles
  
def email_required?
  super && provider.blank?
end

def password_required?
  super && provider.blank?
end
  
end

app/models/wedding.rb
class Wedding < ActiveRecord::Base
  has_many :roles, dependent: :destroy
  has_many :tasks
  has_many :groups
  has_many :users, :through => :roles

  accepts_nested_attributes_for :roles

  validates_presence_of :title
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

  #protect_from_forgery with: :exception

  before_filter :authenticate_user!, :except => [:authorise_facebook, :facebook_oauth_callback]
  
  before_action :configure_permitted_parameters, if: :devise_controller?


  def after_sign_in_path_for(resource)
    user_path(current_user) #your path
  end

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:first_name, :last_name, :email, :password)}
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home

  end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_filter :authenticate_user!, :except => [:authorise_facebook, :facebook_oauth_callback]

  def index
    @user = current_user
    @wedding = Wedding.find(params[:wedding_id])
    @roles = @wedding.roles
    @role = Role.new(:wedding => @wedding)
  end 

  def create
    @user = current_user
    @role = Role.create!(allowed_params)  
    redirect_to wedding_roles_path
  end

  def destroy
    @role = Role.find(params[:id])
    @role.destroy
    redirect_to wedding_roles_path
  end

  private
  def allowed_params
    params.require(:role).permit(:title, :user_id, :role_description, :wedding_id)
  end



end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_filter :authenticate_user!, :except => [:authorise_facebook, :facebook_oauth_callback] 
  before_filter :load_all_task, :only => :index
  
  def new
    @user = current_user
    @task = Task.new
  end 

  def create
    @user = current_user
    @task = Task.new(allowed_params)
    @task.save!
    respond_to do |format|
      format.html {redirect_to tasks_path(@task)}
      format.js 
    end
  end

  def index
    @task = Task.new
  end

  def edit
    @task = Task.find(params[:id]) 
  end

  def update
    @task = Task.find(params[:id])
    @task.update(allowed_params)
    redirect_to tasks_path
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private
  def allowed_params
    params.require(:task).permit(:wedding_id, :title, :task_details, :date_time_due, :location)
  end

  def load_all_task
    @tasks = Task.all
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!, :except => [:authorise_facebook, :facebook_oauth_callback] 
  
  def show
    @user = current_user
  end
 
  def authorise_facebook
    redirect_to facebook_oauth_client.auth_code.authorize_url(
      :redirect_uri => facebook_oauth_callback_url,
      :scope => %w(email).join(","))
  end

  def facebook_oauth_callback
    access_token = facebook_oauth_client.auth_code.get_token(params[:code],
    :redirect_uri => facebook_oauth_callback_url,
    :parse => :query
    )
 
    user_info = JSON(access_token.get('https://graph.facebook.com/me').body).symbolize_keys

    @user = User.find_or_initialize_by(
      :facebook_id => user_info[:id],
      :first_name => user_info[:first_name],
      :last_name => user_info[:last_name],
      :email => user_info[:email]
      )

    @user.access_token = access_token.token 
    @user.provider = "facebook"
    @user.save!
    
    sign_in(@user)
    
    redirect_to user_path
    
  end

  private
  def facebook_oauth_client
    @facebook_oauth_client ||= OAuth2::Client.new(
    WeddingCircle::Application.config.facebook_application_id,
    WeddingCircle::Application.config.facebook_secret,
     :site => "https://graph.facebook.com/",
     :token_url => "/oauth/access_token"
    )
  end

end

app/controllers/weddings_controller.rb
class WeddingsController < ApplicationController
  before_filter :authenticate_user!, :except => [:authorise_facebook, :facebook_oauth_callback] 
  
  def new
    @user = current_user
    @wedding = Wedding.new
    @wedding.roles.build  
  end

  def create
    @user = current_user
    @wedding = Wedding.new(allowed_params)
    @wedding.save!
    redirect_to wedding_path(@wedding)
  end

  def index
    @weddings = Wedding.all
  end

  def weddings
    @weddings = Wedding.all
  end

  def show
    @wedding = Wedding.find(params[:id])
  end

  def edit
    @wedding = Wedding.find(params[:id])
  end

  def update
    @wedding = Wedding.find(params[:id])
    @wedding.update(allowed_params)
    redirect_to wedding_path
  end

  def destroy
    @wedding = Wedding.find(params[:id])
    @wedding.destroy
    redirect_to user_path
  end 

  private
  def allowed_params
    params.require(:wedding).permit(:id, :title, :wedding_date, {roles_attributes: [:id, :title, :user_id, :role_description]})
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/weddings_helper.rb
module WeddingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WeddingCircle</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href='http://fonts.googleapis.com/css?family=Julius+Sans+One' rel='stylesheet' type='text/css'>
  <%#= csrf_meta_tags %>
</head>
<body>

<div class="big-wrapper">
<header>

<h1><%= link_to "Wedding Circle", root_path, :class => "header-title" %></h1>

<nav>
  <ul class="nav-list">
    <% if user_signed_in? %>
    <li>
    <li><%= link_to "Home", root_path %></li>   
    <li><%= link_to "My Dashboard", user_path %></li> 
    <li><%= link_to "My Tasks", tasks_path %></li>
    <li><%= link_to "My Events", weddings_weddings_path %></li>
    <li><%= link_to "Weddings", weddings_path %></li>
      <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
    </li>
    <% else %>
    <li>
      <%= link_to('Login', new_user_session_path) %>  
      <%= link_to('Sign Up', new_user_registration_path) %>  
    </li>
    <% end %>
  </ul>
<nav>

</header>


<main class="main-content">
  <%= yield %>
</main>

</div>

<div class="rings">
  <%= image_tag "rings.png", :id => "rings", :width => "250", :height => "250",  :class => "rings", :alt => "rings" %>
</div>

</body>
</html>

app/views/pages/home.html.erb
<b class="logo-circle"><h2 class="home-message">Plan Your Perfect Wedding!</h2></b>

app/views/roles/index.html.erb
<h2>Join this event? <%= @wedding.title %></h2>

<section class="existing-roles">
<h3>Existing Roles: </h3>

<ul>
  <% @roles.each do |w| %>
    <li><%= w.title %> <%= link_to "Delete", wedding_role_path(@wedding,"#{w.id}"), :method => :delete %></li>
  <% end %>
</ul>

</section>

<section class="create-role">
<h3>Create your role for this wedding:</h3>

<%= form_for @role, url: wedding_roles_path(@wedding), :method => :post do |role_attributes| %>
    
    <%= field_set_tag do %>
      <%#= role_attributes.label :wedding_id %>
      <%= role_attributes.hidden_field :wedding_id %>
    <% end %>

    <%= field_set_tag do %>
      <%= role_attributes.label :title, "Create Role" %>
      <%= role_attributes.text_field :title %>
    <% end %>

    <%= field_set_tag do %>
      <%#= role_attributes.label :user_id, "Role Assigned To =>" %>
      <%= role_attributes.hidden_field :user_id, :value => "#{@user.id}"  %>
    <% end %>

    <%= field_set_tag do %>
      <%= role_attributes.label :role_description %>
      <%= role_attributes.text_area(:role_description, :cols => 50, :rows => 5, :class => "role-description") %>
    <% end %>
    
  <%= submit_tag "Create Role" %>

<% end %>
</section>

app/views/tasks/_form.html.erb
<%= form_for task, url: tasks_path, :remote => true do |f| %>

  <%= field_set_tag do %>
    <%= f.label :wedding_id %>
    <%= f.text_field :wedding_id %>
  <% end %>

  <%= field_set_tag do %>
    <%= f.label :title %>
    <%= f.text_field :title %>
  <% end %>

  <%= field_set_tag do %>
    <%= f.label :task_details %>
    <%= f.text_area(:task_details, :cols => 50, :rows => 5, :class => "task-details") %>
  <% end %>

  <%= field_set_tag do %>
    <%= f.label :date_time_due %>
    <%= f.datetime_select(:date_time_due, { start_year: Time.now.year, end_year: (Time.now.year + 10), order: [:day, :month, :year]}) %>
  <% end %>

  <%= field_set_tag do %>
    <%= f.label :location %>
    <%= f.text_field :location %>
  <% end %>

  <%= submit_tag "Save" %>

<% end %> 

app/views/tasks/_task.html.erb
<div class="task-item">
<ul>
  <li>
    Wedding: <%= task.wedding_id %>
    <%= link_to "Edit Task", edit_task_path("#{task.id}"), :class => "change-task" %>
    <%= link_to "Delete Task", task_path("#{task.id}"), :method => :delete, :class => "change-task" %>
  </li> 
  
  <li>Task: <%= task.title %></li>
  <li>Description: <%= task.task_details %></li>
  <li>Date/Time Due: <%= task.date_time_due.strftime('%d . %B . %Y, at %H:%M') %></li>
  <li>Location: <%= task.location %></li>
</div>
</ul>

app/views/tasks/create.js.erb
$('.new-task-add').append("<%= j(render partial: "tasks/task", locals: {task: @task}) %>");

app/views/tasks/edit.html.erb
<h2>Edit Task: <%= @task.title %></h2>

<%= form_for @task, url: task_path(@task), :method => :put do |f| %>

  <%= field_set_tag do %>
    <%= f.label :wedding_id %>
    <%= f.text_field :wedding_id %>
  <% end %>

  <%= field_set_tag do %>
    <%= f.label :title %>
    <%= f.text_field :title %>
  <% end %>

  <%= field_set_tag do %>
    <%= f.label :task_details %>
    <%= f.text_field :task_details %>
  <% end %>

  <%= field_set_tag do %>
    <%= f.label :date_time_due %>
    <%= f.datetime_select(:date_time_due, { start_year: Time.now.year, end_year: (Time.now.year + 10), order: [:day, :month, :year]}) %>
  <% end %>

  <%= field_set_tag do %>
    <%= f.label :location %>
    <%= f.text_field :location %>
  <% end %>

  <%= submit_tag "Save Changes" %>

<% end %>

app/views/tasks/index.html.erb
<h2>Task List</h2>

<div id="task-form" class="task-form">
  <%= render partial: "tasks/form", locals: {task: @task} %>
</div>

<b id="add-task-form" onclick="addForm()" >Add Task</b>

<% @tasks.each do |t| %>
  <%= render partial: "task", locals: { task: t }  %>
<% end %>

<div class="new-task-add">
</div>

app/views/tasks/new.html.erb
<h2>Create a Task</h2>

<%= render partial: "tasks/form", locals: { task: @task } %>

app/views/users/show.html.erb
<div class="show-user">
<h2>Welcome to your dashboard <%= @user.first_name %> </h2>

<ul>
<li><%= link_to 'Create Wedding', new_wedding_path, :class => "user-links" %></li>
<li><%= link_to 'Join Event', weddings_path, :class => "user-links" %></li>
<li><%= link_to 'Create Task', new_task_path, :class => "user-links" %></li>
</ul>

</div>

app/views/weddings/edit.html.erb
<div class="edit-wedding">

<h2>Edit My Wedding</h2>

<%= form_for @wedding, url: wedding_path(@wedding), :method => :put do |f| %>

  <%= field_set_tag do %>
    <%= f.label :title %>
    <%= f.text_field :title %>
  <% end %>

  <%= field_set_tag do %>
    <%= f.label :wedding_date, "Wedding Date" %>
    <%= f.date_select(:wedding_date, { start_year: Time.now.year, end_year: (Time.now.year + 10), order: [:day, :month, :year]}) %>
  <% end %>

  <%= f.fields_for :roles do |role_attributes| %>
    
    <%= field_set_tag do %>
      <%=role_attributes.label :title, "Create Role" %>
      <%=role_attributes.text_field :title %>
    <% end %>

    <%= field_set_tag do %>
      <%#=role_attributes.label :user_id, "Role Assigned To =>" %>
      <%=role_attributes.hidden_field :user_id %>
    <% end %>

    <%= field_set_tag do %>
      <%= role_attributes.label :role_description %>
      <%= role_attributes.text_area(:role_description, :cols => 50, :rows => 5, :class => "role-description") %>
    <% end %>

  <%= submit_tag "Update" %>

  <% end %>

<% end %>

<div>

app/views/weddings/index.html.erb
<h2>Weddings</h2>

<ul>
  <% @weddings.each do |w| %>
  <li><%= link_to "Join #{w.title}", wedding_roles_path("#{w.id}", @roles) %></li>
  <% end %>
</ul>

app/views/weddings/new.html.erb
<div class="create-my-wedding">
<h2>Create Wedding</h2>

<%= form_for @wedding, url: weddings_path(@wedding), :method => :post do |f| %>

  <%= field_set_tag do %>
    <%= f.label :title %>
    <%= f.text_field :title %>
  <% end %>

  <%= field_set_tag do %>
    <%= f.label :wedding_date, "Wedding Date" %>
    <%= f.date_select(:wedding_date, { start_year: Time.now.year, end_year: (Time.now.year + 10), order: [:day, :month, :year]}) %>
  <% end %>

  <%= f.fields_for :roles do |role_attributes| %>
    
    <%= field_set_tag do %>
      <%=role_attributes.label :title, "Create Role" %>
      <%=role_attributes.text_field :title %>
    <% end %>

    <%= field_set_tag do %>
      <%#=role_attributes.label :user_id, "Role Assigned To =>" %>
      <%=role_attributes.hidden_field :user_id, :value => @user.id %>
    <% end %>

    <%= field_set_tag do %>
      <%= role_attributes.label :role_description, "Role Description" %>
      <%= role_attributes.text_area(:role_description, :cols => 50, :rows => 5, :class => "role-description") %>
    <% end %>
  
  <% end %>

  
  <%= submit_tag "Save" %>

<% end %>

</div>

app/views/weddings/show.html.erb
<div class="show-wedding">
<h2><%= @wedding.title %></h2>

<h3>Wedding Date: <%= @wedding.wedding_date.strftime('%d . %B . %Y') %></h3>

<%= link_to "Edit My Wedding", edit_wedding_path(@wedding), class: "edit-my-wedding" %>
<%= link_to "Delete My Wedding", wedding_path, method: :delete,  class: "edit-my-wedding" %>

<h3>My Role: <%= @wedding.roles.map{|x| x.title}.join(", ") %></h3>

<h3>Role Description: <%= @wedding.roles.map{|x| x.role_description}.join(", ") %></h3>

<div>

app/views/weddings/weddings.html.erb
<h2>My Events</h2>

<ul>
  <% @weddings.each do |w| %>
  <li><%= link_to "#{w.title}", wedding_path("#{w.id}") %></li>
  <% end %>
</ul>